services:
  twitter:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: twitter
    environment:
      - TWITTERAPI_KEY
    labels:
      role: Tools
    network_mode: host
    restart: unless-stopped
