services:
  tavily:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: tavily
    environment:
      - TAVILY_API_KEY
    labels:
      role: Tools
    network_mode: host
    restart: unless-stopped
