export const config = {
    telegramToken: process.env.TELEGRAM_TOKEN || '',
    redisUrl: process.env.REDIS_URL || 'redis://localhost:6379',
    agent_in: 'agent_in',
    agent_out: 'agent_out',
    agent_ctl: 'agent_ctl',
    background_out: 'background_out',
    reminder_out: 'reminder_out',
    gateway_ctl: 'gateway_ctl',
    memory_audit: 'memory_audit',
    tgConsumerGroup: 'tg-bot',
    tgConsumerName: 'bot-1',
    dkronConsumerGroup: 'gateway-dkron',
    dkronConsumerName: 'gateway-1',
    adminId: parseInt(process.env.TG_ADMIN_ID || '0'),
    dkronUrl: process.env.DKRON_URL || 'http://127.0.0.1:18047/v1',
    llamaServerUrl: process.env.LLAMA_SERVER_URL || 'http://127.0.0.1:18080/v1',
    webPort: parseInt(process.env.WEB_PORT || '48329'),
    tgEnabledKey: 'gateway:tg_enabled',
};
